### ISSUE TITLE
return instead of throw on invalid state?

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/fsm-event#1]
Maybe we're being overly strict, and a return suffices. Curious to hear what other people think. - https://github.com/yoshuawuyts/fsm-event/blob/master/index.js#L32

**Comment by yoshuawuyts** [comment]
cc/ @timoxley @hughsk you guys generally make sound decisions, care to lend me your opinion?

**Comment by timoxley** [comment]
Ahh, state machines. This is a rabbithole I enjoy.

No to throwing here, otherwise you force people to try/catch or test state first, e.g. imagine this is hooked up to some button, when user clicks it, let the thing fire whatever events it wants as the state machine will respond once it's in a valid state.

Return true/false is what I've done in the past: https://github.com/timoxley/statemachine/blob/647bef6c836bb0d063e71114d3a5cbb2d4d5e2cf/index.js#L31-L43

My later state machines iterations just ignored invalid state transitions totally, but I'm thinking perhaps special events could be fired when invalid transitions are detected so consumer has control over how to handle such situations.

**Comment by timoxley** [comment]
You can also supplement not throwing by generate a bunch of debugging information so people can easily see what's happening and why.

e.g. here's some optional debug enabled output from running the tests from my unfinished work from ~2 years ago on [statement](https://github.com/timoxley/statement/blob/master/test/actions.js)

![image](https://cloud.githubusercontent.com/assets/43438/7579292/32d7bd1a-f894-11e4-9e18-713b22be2140.png)

**Comment by yoshuawuyts** [comment]
Ooh, thanks for the feedback! What you're saying makes a lot of sense. I think emitting emitting `error` and `data` events might be the right abstraction. Thinking of the following:
- `error` would be fired whenever an incorrect transition is triggered, thinking of passing the `prev` and `next` state to it.
- `data` would be fired on every state transition. Not sure if it should also fire on `:enter` and `:leave` events though.
- debug statements can then be attached as a listener to `data` at the consumer level, which allows for a more clearly scoped debugging experience (`componentName` vs `fsm-event` in `debug`)

Actually considering turning this module into a stream that outputs state somewhat similar to [`stream-fsm`](https://github.com/tmpvar/stream-fsm). The idea of streaming data on the client has somewhat got me; I know that both MS and FB have stream based interfaces in windows and facebook respectably. Since streams are a superset of EventEmitter it may not be completely silly, consumers can always choose to just use events. Am I crazy for wanting to try this?

Also thanks for sharing your previous projects; going to add them to the `See Also` as a reference ^^

**Comment by timoxley** [comment]
> Am I crazy for wanting to try this?

never

**Comment by yoshuawuyts** [comment]
(´・ω・)っ

**Comment by yoshuawuyts** [comment]
released as `fsm-event@2.0.0`
